// TEST JWT SECRET KEY & REFRESH KEY
const JWT_SECRET = process.env.JWT_SECRET_KEY;
const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET_KEY;

// TEST JWT OPTIONS PARAMETERS
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN;
const JWT_EXPIRES_IN_REFRESH = process.env.JWT_REFRESH_TOKEN;
const JWT_ALGORITHM = process.env.JWT_ALGORITHM;

// TEST JWT OPTIONS
const JWT_OPTIONS = {
  algorithm: JWT_ALGORITHM,
  expiresIn: JWT_EXPIRES_IN,
};

// TEST JWT OPTIONS REFRESH
const JWT_REFRESH_OPTIONS = {
  expiresIn: JWT_EXPIRES_IN_REFRESH,
};

module.exports = {
  JWT_SECRET,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_OPTIONS,
  JWT_OPTIONS,
};
